name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: deploy-main
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install haloy
        run: npm i -g haloy@0.1.0-beta.39

      - name: Deploy
        env:
          HALOY_TOKEN: ${{ secrets.HALOY_TOKEN }}
          HETZNER_S3_BUCKET: ${{ secrets.HETZNER_S3_BUCKET }}
          HETZNER_S3_ENDPOINT: ${{ secrets.HETZNER_S3_ENDPOINT }}
          S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
        run: env "HALOY_API_TOKEN_HALOY_XN--2DK_XYZ=$HALOY_TOKEN" haloy deploy
